DEFINE OBJECTS 186
DEFINE OBJECT (noname)    
DEFINE OBJECT PLAYERSDOOR              // Object number -1
DEFINE OBJECT FAKETARGET               // Object number -2
DEFINE OBJECT MISTYDOOR                // Object number -3
DEFINE OBJECT LAUNDRTDOOR1             // Object number -4
DEFINE OBJECT JOEY_DOOR1               // Object number -5
DEFINE OBJECT JOEY_DOOR2               // Object number -6
DEFINE OBJECT ELECTRICGATE             // Object number -7
DEFINE OBJECT DOGFOODOOR01             // Object number -8
DEFINE OBJECT BANKJOBDOOR              // Object number -9
DEFINE OBJECT CHNABANKDOOR             // Object number -10
DEFINE OBJECT BACKDOOR                 // Object number -11
DEFINE OBJECT FUZBALLDOOR              // Object number -12
DEFINE OBJECT SUBWAYGATE               // Object number -13
DEFINE OBJECT TUNNELENTRANCE           // Object number -14
DEFINE OBJECT HELIX_BARRIER            // Object number -15
DEFINE OBJECT PLYSAV_LFTDR_LFT         // Object number -16
DEFINE OBJECT PLYSAV_LFTDR_RGHT        // Object number -17
DEFINE OBJECT FIXED_INSIDE             // Object number -18
DEFINE OBJECT FIXED_OUTSIDE            // Object number -19
DEFINE OBJECT NEWTOWERDOOR1            // Object number -20
DEFINE OBJECT COLUMBIANGATE            // Object number -21
DEFINE OBJECT AIRPORTDOOR1             // Object number -22
DEFINE OBJECT AIRPORTDOOR2             // Object number -23
DEFINE OBJECT BODYARMOUR               // Object number -24
DEFINE OBJECT INDHELIX_BARRIER         // Object number -25
DEFINE OBJECT LOD_LAND014              // Object number -26
DEFINE OBJECT INFO                     // Object number -27
DEFINE OBJECT HEALTH                   // Object number -28
DEFINE OBJECT ADRENALINE               // Object number -29
DEFINE OBJECT BRIBE                    // Object number -30
DEFINE OBJECT KILLFRENZY               // Object number -31
DEFINE OBJECT LINE                     // Object number -32
DEFINE OBJECT BONUS                    // Object number -33
DEFINE OBJECT BRIDGEFUKA               // Object number -34
DEFINE OBJECT BRIDGEFUKB               // Object number -35
DEFINE OBJECT TRAFFICLIGHT1            // Object number -36
DEFINE OBJECT RD_SRROAD2A50            // Object number -37
DEFINE OBJECT RD_SRROAD2A20            // Object number -38
DEFINE OBJECT RD_SRROAD2A10            // Object number -39
DEFINE OBJECT RD_CROSSRDA1RW22         // Object number -40
DEFINE OBJECT RD_CROSSROADSA24         // Object number -41
DEFINE OBJECT COM_CUST_ROADS25         // Object number -42
DEFINE OBJECT VEG_TREE3                // Object number -43
DEFINE OBJECT DOUBLESTREETLGHT1        // Object number -44
DEFINE OBJECT VEG_TREEA3               // Object number -45
DEFINE OBJECT VEG_TREENEW17            // Object number -46
DEFINE OBJECT STREETLAMP1              // Object number -47
DEFINE OBJECT BOLLARDLIGHT             // Object number -48
DEFINE OBJECT KB_SCRAP_5               // Object number -49
DEFINE OBJECT POLICETENKB1             // Object number -50
DEFINE OBJECT SCRAPERKB3_NIT           // Object number -51
DEFINE OBJECT CHUNK5LAND               // Object number -52
DEFINE OBJECT POLICEALLY               // Object number -53
DEFINE OBJECT POLICE_COM               // Object number -54
DEFINE OBJECT RD_CROSSRDA1W22          // Object number -55
DEFINE OBJECT TREEPATCHKB7             // Object number -56
DEFINE OBJECT ROADPLANTERKB3           // Object number -57
DEFINE OBJECT ROADPLANTERKB1           // Object number -58
DEFINE OBJECT RD_ROAD3A50              // Object number -59
DEFINE OBJECT AMCO_FLOOR               // Object number -60
DEFINE OBJECT RD_ROAD2A20              // Object number -61
DEFINE OBJECT BROADWAYBUILD2           // Object number -62
DEFINE OBJECT BROADWAYBUILD            // Object number -63
DEFINE OBJECT AREA5BUILD2              // Object number -64
DEFINE OBJECT COMSWCENTRALBLD7         // Object number -65
DEFINE OBJECT PAPERMACHN01             // Object number -66
DEFINE OBJECT COMSWCENTRALBLD6         // Object number -67
DEFINE OBJECT COM_21WAY5               // Object number -68
DEFINE OBJECT COM_21WAY50              // Object number -69
DEFINE OBJECT COM_21WAY10              // Object number -70
DEFINE OBJECT CM1WAYCROSSCOM           // Object number -71
DEFINE OBJECT COM_21WAY20              // Object number -72
DEFINE OBJECT TW@T_CAFE                // Object number -73
DEFINE OBJECT VEG_BUSH14               // Object number -74
DEFINE OBJECT TREEPATCHTTWRS           // Object number -75
DEFINE OBJECT FLATIRON1                // Object number -76
DEFINE OBJECT BLOCK4_GROUND01          // Object number -77
DEFINE OBJECT PLANTER_SHORT            // Object number -78
DEFINE OBJECT COM_RVROADS52            // Object number -79
DEFINE OBJECT ROAD_BROADWAY04          // Object number -80
DEFINE OBJECT COM_ROADSRV              // Object number -81
DEFINE OBJECT RD_ROAD1A20              // Object number -82
DEFINE OBJECT RD_CROSSROADS11          // Object number -83
DEFINE OBJECT OFIS_BILDKB_4            // Object number -84
DEFINE OBJECT RD_ROAD1A10              // Object number -85
DEFINE OBJECT COM_ROADKB23             // Object number -86
DEFINE OBJECT COM_CUST_ROADS57         // Object number -87
DEFINE OBJECT COM_ROADKB22             // Object number -88
DEFINE OBJECT KB_UNDERPASS             // Object number -89
DEFINE OBJECT MUSEUM                   // Object number -90
DEFINE OBJECT NBCOM_ROADKB01           // Object number -91
DEFINE OBJECT BVBRIDGSPPRT01           // Object number -92
DEFINE OBJECT FLATIRON1B               // Object number -93
DEFINE OBJECT NBBRIDGCABLS01           // Object number -94
DEFINE OBJECT NBBRIDGERDB              // Object number -95
DEFINE OBJECT NBBRIDGERDA              // Object number -96
DEFINE OBJECT OVERPASS_COMSE           // Object number -97
DEFINE OBJECT COM_LANDNEW221B          // Object number -98
DEFINE OBJECT COM_LANDNEW221           // Object number -99
DEFINE OBJECT LODTIRON1B               // Object number -100
DEFINE OBJECT KB_OFIS1                 // Object number -101
DEFINE OBJECT COMTREEPATCHPRK          // Object number -102
DEFINE OBJECT HOTEL2                   // Object number -103
DEFINE OBJECT UNDERGROUND_OVER7        // Object number -104
DEFINE OBJECT RD_ROAD1A50              // Object number -105
DEFINE OBJECT KBPLANTER4               // Object number -106
DEFINE OBJECT BLOCK4_SCRAPERL0         // Object number -107
DEFINE OBJECT COM_ROADKB12             // Object number -108
DEFINE OBJECT PLANTERBTM_1             // Object number -109
DEFINE OBJECT LODRIDGSPPRT01           // Object number -110
DEFINE OBJECT LODOM_ROADKB01           // Object number -111
DEFINE OBJECT LODRIDGERDA              // Object number -112
DEFINE OBJECT LODRIDGERDB              // Object number -113
DEFINE OBJECT LODRIDGCABLS01           // Object number -114
DEFINE OBJECT IND_CUSTOMROAD003        // Object number -115
DEFINE OBJECT KMRICNDO01               // Object number -116
DEFINE OBJECT KMRICNDO02               // Object number -117
DEFINE OBJECT COM_DOCKSAA              // Object number -118
DEFINE OBJECT COM_PIER3                // Object number -119
DEFINE OBJECT GRD_OVERPASS19KB         // Object number -120
DEFINE OBJECT GRD_OVERPASS19BKB        // Object number -121
DEFINE OBJECT COM_DOCKSB               // Object number -122
DEFINE OBJECT NEWDOCKBUILDING2         // Object number -123
DEFINE OBJECT NEWDOCKBUILDING          // Object number -124
DEFINE OBJECT NBBRIDGFK2               // Object number -125
DEFINE OBJECT DAMGBRIDGERDB            // Object number -126
DEFINE OBJECT DAMGBBRIDGERDA           // Object number -127
DEFINE OBJECT LODRIDGFK2               // Object number -128
DEFINE OBJECT LODGBRIDGERDB            // Object number -129
DEFINE OBJECT LODGBBRIDGERDA           // Object number -130
DEFINE OBJECT INDHIBUILD3              // Object number -131
DEFINE OBJECT LUIGICLUBOUT             // Object number -132
DEFINE OBJECT LUIGIINEERCLUB           // Object number -133
DEFINE OBJECT JOGARAGEEXT              // Object number -134
DEFINE OBJECT JOGARAGEINT              // Object number -135
DEFINE OBJECT POLICEBALLSIGNS          // Object number -136
DEFINE OBJECT NOODLESBOX               // Object number -137
DEFINE OBJECT IND_NEWRIZZOS            // Object number -138
DEFINE OBJECT BRIEFCASE                // Object number -139
DEFINE OBJECT SALVSDETAIL              // Object number -140
DEFINE OBJECT SWANK_INSIDE             // Object number -141
DEFINE OBJECT FRANKSCLB02              // Object number -142
DEFINE OBJECT FSHFCTRY_DSTRYD          // Object number -143
DEFINE OBJECT FISH01                   // Object number -144
DEFINE OBJECT FISHFCTORY               // Object number -145
DEFINE OBJECT IND_LAND089C             // Object number -146
DEFINE OBJECT MAK_SEMTECH              // Object number -147
DEFINE OBJECT MAK_BOMB01               // Object number -148
DEFINE OBJECT CS8_DOOR                 // Object number -149
DEFINE OBJECT BARREL4                  // Object number -150
DEFINE OBJECT RUSTSHIP_STRUCTURE       // Object number -151
DEFINE OBJECT LODTSHIP_STRUCTURE       // Object number -152
DEFINE OBJECT BOATRAMP1                // Object number -153
DEFINE OBJECT DONKEYMAG                // Object number -154
DEFINE OBJECT CONDO_IVY                // Object number -155
DEFINE OBJECT IND_CUSTOMROAD016        // Object number -156
DEFINE OBJECT POLICE_CELHOLE           // Object number -157
DEFINE OBJECT POLICE_CELL_WALL         // Object number -158
DEFINE OBJECT CASINO_GARDEN            // Object number -159
DEFINE OBJECT RUBBLE01                 // Object number -160
DEFINE OBJECT RUBBLE02                 // Object number -161
DEFINE OBJECT CONVSTORE01              // Object number -162
DEFINE OBJECT CONVSTRE_DMGE01          // Object number -163
DEFINE OBJECT CONVSTORE01_DOOR         // Object number -164
DEFINE OBJECT TOILET                   // Object number -165
DEFINE OBJECT SAFEHOUSE                // Object number -166
DEFINE OBJECT FILES                    // Object number -167
DEFINE OBJECT TOILET_CUBICLE_DR2       // Object number -168
DEFINE OBJECT BARREL2                  // Object number -169
DEFINE OBJECT BODYCAST                 // Object number -170
DEFINE OBJECT TSHRORCKGRDN             // Object number -171
DEFINE OBJECT TSHRORCKGRDN_ALFAS       // Object number -172
DEFINE OBJECT DEADMAN1                 // Object number -173
DEFINE OBJECT DEADMANOBLOOD            // Object number -174
DEFINE OBJECT CSITECUTSCENE            // Object number -175
DEFINE OBJECT SCAFFOLDLIFT             // Object number -176
DEFINE OBJECT BROKEN_INSIDE            // Object number -177
DEFINE OBJECT BROKEN_OUTSIDE           // Object number -178
DEFINE OBJECT COFFEE                   // Object number -179
DEFINE OBJECT PACKAGELARGE             // Object number -180
DEFINE OBJECT BOUY                     // Object number -181
DEFINE OBJECT NEW_COLMANSN             // Object number -182
DEFINE OBJECT LANDPART15               // Object number -183
DEFINE OBJECT SECURITY_HUT             // Object number -184
DEFINE OBJECT COLUMANSION_WALL         // Object number -185

DEFINE MISSIONS 40
DEFINE MISSION 0 AT @M00_INTRO          		// Formerly INTRO
DEFINE MISSION 1 AT @M01_HOSPITALHELP			// Formerly HEALTH           
DEFINE MISSION 2 AT @M02_POLICEHELP			// Formerly WANTED           
DEFINE MISSION 3 AT @M03_DIABLODESTRUCTION		// Formerly RC1              
DEFINE MISSION 4 AT @M04_MAFIAMASSACRE			// Formerly RC2
DEFINE MISSION 5 AT @M05_RUMPORAMPAGE			// Formerly RC3                
DEFINE MISSION 6 AT @M06_CASINOCALAMITY			// Formerly RC4                
DEFINE MISSION 7 AT @M07_PATRIOTPLAYGROUND		// Formerly T4X4_1           
DEFINE MISSION 8 AT @M08_ARIDEINTHEPARK			// Formerly T4X4_2           
DEFINE MISSION 9 AT @M09_GRIPPED			// Formerly T4X4_3           
DEFINE MISSION 10 AT @M10_MULTISTOREYMAYHEM		// Formerly MAYHEM          
DEFINE MISSION 11 AT @M11_PARAMEDIC			// Formerly AMBULAN         
DEFINE MISSION 12 AT @M12_FIREFIGHTER			// Formerly FIRETRU         
DEFINE MISSION 13 AT @M13_VIGILANTE			// Formerly COPCAR          
DEFINE MISSION 14 AT @M14_TAXI				// Formerly TAXI            
DEFINE MISSION 15 AT @M15_THECROOK			// Formerly MEAT1           
DEFINE MISSION 16 AT @M16_THETHIEVES			// Formerly MEAT2           
DEFINE MISSION 17 AT @M17_THEWIFE			// Formerly MEAT3           
DEFINE MISSION 18 AT @M18_HERLOVER			// Formerly MEAT4           
DEFINE MISSION 19 AT @M19_GIVEMELIBERTY			// Formerly EIGHT           
DEFINE MISSION 20 AT @M20_DONTSPANKMABITCHUP		// Formerly LUIGI2           
DEFINE MISSION 21 AT @M21_DRIVEMISTYFORME		// Formerly LUIGI3          
DEFINE MISSION 22 AT @M22_PUMPACTIONPIMP		// Formerly LUIGI4          
DEFINE MISSION 23 AT @M23_THEFUZZBALL			// Formerly LUIGI5          
DEFINE MISSION 24 AT @M24_MIKELIPSLASTLUNCH		// Formerly JOEY1           
DEFINE MISSION 25 AT @M25_FAREWELLCHUNKYLEECHONG	// Formerly JOEY2           
DEFINE MISSION 26 AT @M26_VANHEIST			// Formerly JOEY3           
DEFINE MISSION 27 AT @M27_CIPRIANISCHAUFFEUR		// Formerly JOEY4           
DEFINE MISSION 28 AT @M28_DEADSKUNKINTHETRUNK		// Formerly JOEY5           
DEFINE MISSION 29 AT @M29_THEGETAWAY			// Formerly JOEY6           
DEFINE MISSION 30 AT @M30_TAKINGOUTTHELAUNDRY		// Formerly TONI1           
DEFINE MISSION 31 AT @M31_THEPICKUP			// Formerly TONI2           
DEFINE MISSION 32 AT @M32_SALVATORESCALLEDAMEETING	// Formerly TONI3           
DEFINE MISSION 33 AT @M33_TRIADSANDTRIBULATIONS		// Formerly TONI4           
DEFINE MISSION 34 AT @M34_BLOWFISH			// Formerly TONI5           
DEFINE MISSION 35 AT @M35_CHAPERONE			// Formerly FRANK1          
DEFINE MISSION 36 AT @M36_CUTTINGTHEGRASS		// Formerly FRANK2          
DEFINE MISSION 37 AT @M37_BOMBDABASEACTI		// Formerly FRANK21         
DEFINE MISSION 38 AT @M38_BOMBDABASEACTII		// Formerly FRANK3          
DEFINE MISSION 39 AT @M39_LASTREQUESTS			// Formerly FRANK4          
//DEFINE MISSION 40 AT @M40_TURISMO			// Formerly DIABLO1         
//DEFINE MISSION 41 AT @M41_ISCREAMYOUSCREAM		// Formerly DIABLO2         
//DEFINE MISSION 42 AT @M42_TRIALBYFIRE			// Formerly DIABLO3         
//DEFINE MISSION 43 AT @M43_BIGNVEINY			// Formerly DIABLO4         
//DEFINE MISSION 44 AT @M44_SAYONARASALVATORE		// Formerly ASUKA1          
//DEFINE MISSION 45 AT @M45_UNDERSURVEILLANCE		// Formerly ASUKA2          
//DEFINE MISSION 46 AT @M46_PAPARAZZIPURGE		// Formerly ASUKA3          
//DEFINE MISSION 47 AT @M47_PAYDAYFORRAY			// Formerly ASUKA4          
//DEFINE MISSION 48 AT @M48_TWOFACEDTANNER		// Formerly ASUKA5          
//DEFINE MISSION 49 AT @M49_KANBUBUSTOUT			// Formerly KENJI1          
//DEFINE MISSION 50 AT @M50_GRANDTHEFTAUTO		// Formerly KENJI2          
//DEFINE MISSION 51 AT @M51_DEALSTEAL			// Formerly KENJI3          
//DEFINE MISSION 52 AT @M52_SHIMA				// Formerly KENJI4          
//DEFINE MISSION 53 AT @M53_SMACKDOWN			// Formerly KENJI5          
//DEFINE MISSION 54 AT @M54_SILENCETHESNEAK		// Formerly RAY1            
//DEFINE MISSION 55 AT @M55_ARMSSHORTAGE			// Formerly RAY2            
//DEFINE MISSION 56 AT @M56_EVIDENCEDASH			// Formerly RAY3            
//DEFINE MISSION 57 AT @M57_GONEFISHING			// Formerly RAY4            
//DEFINE MISSION 58 AT @M58_PLASTERBLASTER		// Formerly RAY5            
//DEFINE MISSION 59 AT @M59_MARKEDMAN			// Formerly RAY6            
//DEFINE MISSION 60 AT @M60_LIBERATOR			// Formerly LOVE1           
//DEFINE MISSION 61 AT @M61_WAKAGASHIRAWIPEOUT		// Formerly LOVE2           
//DEFINE MISSION 62 AT @M62_ADROPINTHEOCEAN		// Formerly LOVE3           
//DEFINE MISSION 63 AT @M63_BLINGBLINGSCRAMBLE		// Formerly YARD1           
//DEFINE MISSION 64 AT @M64_UZIRIDER			// Formerly YARD2           
//DEFINE MISSION 65 AT @M65_GANGCARROUNDUP		// Formerly YARD3           
//DEFINE MISSION 66 AT @M66_KINGDOMCOME			// Formerly YARD4           
//DEFINE MISSION 67 AT @M67_GRANDTHEFTAERO		// Formerly LOVE4           
//DEFINE MISSION 68 AT @M68_ESCORTSERVICE			// Formerly LOVE5           
//DEFINE MISSION 69 AT @M69_DECOY				// Formerly LOVE6           
//DEFINE MISSION 70 AT @M70_LOVESDISAPPERANCE		// Formerly LOVE7           
//DEFINE MISSION 71 AT @M71_BAIT				// Formerly ASUSB1          
//DEFINE MISSION 72 AT @M72_ESPRESSO2GO			// Formerly ASUSB2          
//DEFINE MISSION 73 AT @M73_SAM				// Formerly ASUSB3          
//DEFINE MISSION 74 AT @M74_UZIMONEY			// Formerly HOOD1           
//DEFINE MISSION 75 AT @M75_TOYMINATOR			// Formerly HOOD2           
//DEFINE MISSION 76 AT @M76_RIGGEDTOBLOW			// Formerly HOOD3           
//DEFINE MISSION 77 AT @M77_BULLIONRUN			// Formerly HOOD4           
//DEFINE MISSION 78 AT @M78_RUMBLE			// Formerly HOOD5           
//DEFINE MISSION 79 AT @M79_THEEXCHANGE			// Formerly CAT11          

CONST
// <constant name> = <constant value>

//driving styles
DRIVINGMODE_STOPFORCARS = 0
DRIVINGMODE_SLOWDOWNFORCARS = 1
DRIVINGMODE_AVOIDCARS = 2

//door statuses
CARLOCK_UNLOCKED = 1
CARLOCK_LOCKED = 2
CARLOCK_LOCKOUT_PLAYER_ONLY = 3
CARLOCK_LOCKED_PLAYER_INSIDE = 4
CARLOCK_FORCE_SHUT_DOORS = 6

//carbomb statuses
CARBOMB_TIMED = 1
CARBOMB_ONIGNITION = 2
CARBOMB_REMOTE = 3
CARBOMB_TIMEDACTIVE = 4
CARBOMB_ONIGNITIONACTIVE = 5

//vehicles
CAR_BOXTER = 92 // Stinger
CAR_FIRETRUCK = 97
CAR_INFERNUS = 101
CAR_CHEETAH = 105
CAR_AMBULANCE = 106
CAR_FBI = 107
CAR_BUGGY = 114 // BF Injection
CAR_CORPSE = 115
CAR_POLICE = 116
CAR_ENFORCER = 117
CAR_SECURICAR = 118
CAR_BANSHEE = 119
BOAT_PREDATOR = 120
CAR_BUS = 121
CAR_RHINO = 122
CAR_BARRACKS = 123
TRAIN_SUBWAY = 124
HELI_POLICE = 125
PLANE_DODO = 126
CAR_COACH = 127
CAR_RCBANDIT = 131
PLANE_AIRTRAIN = 140

//pedtypes
PEDTYPE_CIVMALE = 4
PEDTYPE_CIVFEMALE = 5
PEDTYPE_GANG_MAFIA = 7
PEDTYPE_GANG_TRIAD = 8
PEDTYPE_GANG_DIABLO = 9
PEDTYPE_GANG_COLOMBIAN = 12
PEDTYPE_GANG_HOOD = 13
PEDTYPE_PROSTITUTE = 20
PEDTYPE_SPECIAL = 21

//peds
// PED_GANG_COLOMBIAN_A = #GANG11

//pedstats
PEDSTAT_GEEK_GUY = 14
PEDSTAT_TOUGH_GUY = 16

//weapon types
WEAPONTYPE_UNARMED = 0
WEAPONTYPE_BASEBALLBAT = 1
WEAPONTYPE_PISTOL = 2
WEAPONTYPE_UZI = 3
WEAPONTYPE_SHOTGUN = 4
WEAPONTYPE_CHAINGUN = 5
WEAPONTYPE_M16 = 6
WEAPONTYPE_SNIPERRIFLE = 7
WEAPONTYPE_DETONATOR = 12

//threats
THREAT_PLAYER1 = 1
THREAT_PLAYER2 = 2
THREAT_PLAYER3 = 4
THREAT_PLAYER4 = 8
THREAT_CIVMALE = 16
THREAT_CIVFEMALE = 32
THREAT_COP = 64
THREAT_GANG_MAFIA = 128
THREAT_GANG_TRIAD = 256
THREAT_GANG_DIABLO = 512
THREAT_GANG_YAKUZA = 1024
THREAT_GANG_YARDIE = 2048
THREAT_GANG_COLOMBIAN = 4096
THREAT_GANG_HOOD = 8192
THREAT_EMERGENCY = 65536
THREAT_PROSTITUTE = 131072
THREAT_CRIMINAL = 262144
THREAT_SPECIAL = 524288
THREAT_GUN = 1048576
THREAT_COP_CAR = 2097152
THREAT_FAST_CAR = 4194304
THREAT_FIREMAN = 16777216

//camera modes
BEHINDCAR = 3
FIXED = 15

//camera switchstyles
INTERPOLATION = 1
JUMP_CUT = 2

//control pads
PAD1 = 0

//keys
SQUARE = 14
CROSS = 16
RIGHTSHOCK = 19

//animations (waitstates)
WAITSTATE_FALSE = 0
WAITSTATE_PLAYANIM_DUCK = 14
WAITSTATE_PLAYANIM_CHAT = 19

//animations (walkstyles)
ANIM_GANG2_PED = 9
ANIM_SEXY_WOMANPED = 15
ANIM_PANIC_CHUNKYPED = 18

//explosions
EXPLOSION_CAR = 3
EXPLOSION_HELI = 5

//radar icons
RADAR_SPRITE_ASUKA = 1
RADAR_SPRITE_BOMB = 2
RADAR_SPRITE_EIGHT = 7
RADAR_SPRITE_JOEY = 10
RADAR_SPRITE_LUIGI = 13
RADAR_SPRITE_SAL = 16
RADAR_SPRITE_SPRAY = 18
RADAR_SPRITE_TONY = 19
RADAR_SPRITE_WEAPON = 20

//blip display
MARKER_ONLY = 1
BLIP_ONLY = 2
BOTH = 3

//hud items
HUD_FLASH_HEALTH = 4
HUD_FLASH_RADAR = 8

//time of day
DAY = 1
NIGHT = 0

//weather
WEATHER_SUNNY = 0
WEATHER_CLOUDY = 1
WEATHER_RAINY = 2
WEATHER_FOGGY = 3

//particles
POBJECT_PAVEMENT_STEAM_SLOWMOTION = 1
POBJECT_WALL_STEAM_SLOWMOTION = 3
POBJECT_DRY_ICE_SLOWMOTION = 12
POBJECT_FIREBALL_AND_SMOKE = 15
POBJECT_CATALINAS_GUNFLASH = 18
POBJECT_CATALINAS_SHOTGUNFLASH = 19

//shadows
SHADOW_EXPLOSION = 3

//islands
LEVEL_INDUSTRIAL = 1 // Portland
LEVEL_COMMERCIAL = 2 // Staunton
LEVEL_SUBURBAN = 3 // Shoreside Vale

//sounds
sound_test_1 = 0
SOUND_RAVE_LOOP_INDUSTRIAL_L = 73
SOUND_INJURED_PED_MALE_OUCH_S = 78
SOUND_INJURED_PED_MALE_OUCH_L = 79
SOUND_INJURED_PED_FEMALE_OUCH_S = 80
SOUND_INJURED_PED_FEMALE_OUCH_L = 81
SOUND_PART_MISSION_COMPLETE = 94
SOUND_CHUNKY_RUN_SHOUT = 95
SOUND_SECURITY_GUARD_RUN_AWAY_SHOUT = 96
SOUND_SWAT_PED_SHOUT = 101
SOUND_PRETEND_FIRE_LOOP = 102

//radio stations
HEAD_RADIO = 0
DOUBLE_CLEFF_FM = 1
RISE_FM = 3

//pickups
PICKUP_IN_SHOP = 1
PICKUP_ONCE = 3
PICKUP_ON_STREET_SLOW = 14

//corona types
CORONATYPE_HEX = 5

//flare types
FLARETYPE_NONE = 0

//status text
COUNTER_DISPLAY_BAR = 1

//garages
GARAGE_COLLECTSPECIFICCARS = 7
GARAGE_MISSION_KEEPCAR = 14
GARAGE_FOR_SCRIPT_TO_OPEN_AND_CLOSE = 19
GARAGE_MISSION_KEEPCAR_REMAINCLOSED = 21
END



//-------------MAIN---------------
03A4: name_thread 'MAIN' 
0053: create_player #NULL at 811.875 -939.9375 35.75 store_to $PLAYER_CHAR 
0171: set_player $PLAYER_CHAR z_angle_to 180.0 
01F5: $PLAYER_ACTOR = create_emulated_actor_from_player $PLAYER_CHAR 
gosub @DEBUG_VARIABLES
042C: set_total_missions_to 73 
030D: set_total_mission_points_to 154 
if
	$DEBUGUNLOCKISLANDS == 1
then
	01F0: set_max_wanted_level_to 6
else
	01F0: set_max_wanted_level_to 4 
end

gosub @VARIABLE_INIT
gosub @SETUP_DYNAMIC_OBJECTS
gosub @INIT_SPECIAL_OBJECTS
gosub @GARAGES_INIT
gosub @TRAFFIC_INFO
gosub @CAR_GENERATORS
gosub @MAIN_PICKUPS
gosub @HIDDEN_PACKAGES

gosub @INIT_SOUND_LOOPS

0111: set_wasted_busted_check_to 1

gosub @INIT_MISSION_LOCATIONS
gosub @INIT_THREADS


// Targetable objects require player to be defined!
035D: make_object $FAKETARGET1 targetable 
035D: make_object $FAKETARGET2 targetable 
035D: make_object $FAKETARGET3 targetable 
if 
	0256:   is_player $PLAYER_CHAR defined 
then
	01B4: set_player $PLAYER_CHAR controllable 0
end
0169: set_fade_color 0 0 0 
016A: fade 0 for 0 ms 
0417: start_mission M00_INTRO
004F: create_thread @PORTLAND_SAVE
004F: create_thread @STAUNTON_SAVE
004F: create_thread @SSV_SAVE
004F: create_thread @PORTLAND_RESTART
004F: create_thread @STAUNTON_RESTART
004F: create_thread @SSV_RESTART
004F: create_thread @WASTED_LOOP
004F: create_thread @BUSTED_LOOP
if
	0256:   is_player $PLAYER_CHAR defined 
then
	01B4: set_player $PLAYER_CHAR controllable 1
end
while true
	wait 1000 ms
	gosub @CHECK_INFO_PICKUPS
end // main loop that constantly runs

//Main threads
{$INCLUDE camera.sc}   	//CAMERA
{$INCLUDE car_gen.sc}  	//CAR_GENERATORS
{$INCLUDE debug.sc}    	//DEBUG_VARIABLES - STARTER - COORDS
{$INCLUDE gates.sc}    	//FISH_FACTORY_GATE - DOG_FOOD_FACTORY_GATE - POLICE_GATE1 - POLICE_GATE2 - COLOMBIAN_GATE - PHILS_GATE - COLOMBIAN_GATE2
{$INCLUDE genstuf.sc}  	//GENSTUFF - COBBLERS - CHECK_INFO_PICKUP - CHECK_INFO_PICKUP_2 - IND_AMMU - FISH_FACTORY_GEN - TRAMP_TUNNEL - IND_SOUND - DOG_SOUND - COM_AMMU - COM_CAR_PARK
{$INCLUDE help.sc}	//LUIGI_MESSAGE - BIKE_HELP - PISTOL_MESSAGE - UZI_MESSAGE - IMP_EXP_PAGER - EMERGENCY_CRANE_PAGER - VAN_HEIST_GARAGE_PAGER - JOEYS_BUGGY_LOOP - TONI5_FLAMES_LOOP - BLOB_HELP_LOOP - TONI4_PAGER_LOOP - TONI5_PAGER_LOOP - CLOSE_FUZZ_DOORS - CLOSE_ASUKA1_DOOR
{$INCLUDE hj.sc}	//INSANE_STUNT
{$INCLUDE import.sc}   	//IE_GARAGE_IND - EMERGENCY_CRANE - IE_GARAGE_SUB - PACKAGE_SNIFFER
{$INCLUDE init.sc}	//SETUP_DYNAMIC_OBJECTS - INIT_SPECIAL_OBJECTS - GARAGES_INIT - TRAFFIC_INFO - VARIABLE_INIT - INIT_MISSION_LOCATIONS - INIT_THREADS - INIT_SOUND_LOOPS
{$INCLUDE packages.sc}	//HIDDEN_PACKAGES
{$INCLUDE pickups.sc}  	//MAIN_PICKUPS - CHECK_INFO_PICKUPS
{$INCLUDE rampage.sc}  	//KILL_FRENZY
{$INCLUDE rewards.sc}  	//ALL_REWARDS
{$INCLUDE save.sc}     	//PORTLAND_SAVE - STAUNTON_SAVE - SSV_SAVE - PORTLAND_RESTART - STAUNTON_RESTART - SSV_RESTART
{$INCLUDE triggers.sc} 	//All mission triggers
{$INCLUDE usj.sc}      	//USJ








//Missions
{$INCLUDE 00_intro.sc} // M00_INTRO
{$INCLUDE 01_health.sc} // M01_HOSPITALHELP
{$INCLUDE 02_wanted.sc} // M02_POLICEHELP
{$INCLUDE 03_rc1.sc} // M03_DIABLODESTRUCTION
{$INCLUDE 04_rc2.sc} // M04_MAFIAMASSACRE
{$INCLUDE 05_rc3.sc} // M05_RUMPORAMPAGE
{$INCLUDE 06_rc4.sc} // M06_CASINOCALAMITY
{$INCLUDE 07_4x4_1.sc} // M07_PATRIOTPLAYGROUND
{$INCLUDE 08_4x4_2.sc} // M08_ARIDEINTHEPARK
{$INCLUDE 09_4x4_3.sc} // M09_GRIPPED
{$INCLUDE 10_mayhem1.sc} // M10_MULTISTOREYMAYHEM
{$INCLUDE 11_ambulance.sc} // M11_PARAMEDIC
{$INCLUDE 12_firetruck.sc} // M12_FIREFIGHTER
{$INCLUDE 13_copcar.sc} // M13_VIGILANTE
{$INCLUDE 14_taxi.sc} // M14_TAXI
{$INCLUDE 15_meat1.sc} // M15_THECROOK
{$INCLUDE 16_meat2.sc} // M16_THETHIEVES
{$INCLUDE 17_meat3.sc} // M17_THEWIFE
{$INCLUDE 18_meat4.sc} // M18_HERLOVER
{$INCLUDE 19_8ball.sc} // M19_GIVEMELIBERTY
{$INCLUDE 20_luigi2.sc} // M20_DONTSPANKMABITCHUP
{$INCLUDE 21_luigi3.sc} // M21_DRIVEMISTYFORME
{$INCLUDE dummymissions.sc} // M22_PUMPACTIONPIMP  M23_THEFUZZBALL  These don't exist, but need to be defined to avoid screwing up the mission list
{$INCLUDE 24_joey1.sc} // M24_MIKELIPSLASTLUNCH
{$INCLUDE 25_joey2.sc} // M25_FAREWELLCHUNKYLEECHONG
{$INCLUDE 26_joey3.sc} // M26_VANHEIST
{$INCLUDE 27_joey4.sc} // M27_CIPRIANISCHAUFFEUR
{$INCLUDE dummymissions2.sc} // M28_DEADSKUNKINTHETRUNK  M29_THEGETAWAY  These don't exist, but need to be defined to avoid screwing up the mission list
{$INCLUDE 30_toni1.sc} // M30_TAKINGOUTTHELAUNDRY
{$INCLUDE 31_toni2.sc} // M31_THEPICKUP
{$INCLUDE 32_toni3.sc} // M32_SALVATORESCALLEDAMEETING
{$INCLUDE 33_toni4.sc} // M33_TRIADSANDTRIBULATIONS
{$INCLUDE 34_toni5.sc} // M34_BLOWFISH
{$INCLUDE 35_frank1.sc} // M35_CHAPERONE
{$INCLUDE 36_frank2.sc} // M36_CUTTINGTHEGRASS
{$INCLUDE 37_frank2.1.sc} // M37_BOMBDABASEACTI
{$INCLUDE 38_frank3.sc} // M38_BOMBDABASEACTII
{$INCLUDE 39_frank4.sc} // M39_LASTREQUESTS
